name: Test deployment

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3